const COLORS = [
  "#76D201",
  "#FC8F32",
  "#FF3EA5",
  "#59CBE8",
  "#BB29BB",
  "#0A6202",
  "#FFCC15",
  "#FF6D6A",
  "#517EF5",
  "#717BA7",
  "#27415E",
];

const topComments = [
  {
    username: "brian",
    likes: "+1",
    id: 11,
    point: { x: 600, y: 100 },
    value: "im so excited!!! lets gooooooo",
    commentTimestamp: 1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "gwg.eth",
    likes: "+29",
    id: 12,
    point: { x: 620, y: 150 },
    value: "is this the last season?",
    commentTimestamp: 1.49,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "mk.eth",
    likes: "-10",
    id: 13,
    point: { x: 590, y: 200 },
    value: "it better not be bruh",
    commentTimestamp: 1.49,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "matt",
    likes: "+93",
    id: 1,
    point: { x: 50, y: 50 },
    value: `I have a hypothesis on why sam is going to die. Vecna preys on people who are mentally weaker right, hence all the kids going to therapy at school and how they're suffering from all these symptons. its because vecna hijacks peoples brains like how El does.`,
    commentTimestamp: 1.51,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "br1an.eth",
    likes: "+6",
    id: 2,
    point: { x: 50, y: 320 },
    value:
      "bipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    commentTimestamp: 1.54,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "steveFan",
    likes: "-2",
    id: 4,
    point: { x: 1100, y: 50 },
    value:
      "c heard that the actors Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    commentTimestamp: 1.52,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "brian",
    likes: "+1",
    id: 6,
    point: { x: 1100, y: 520 },
    value: "do yall actually think they're killing Alex this season?",
    commentTimestamp: 1.5,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "gwg.eth",
    likes: "+29",
    id: 7,
    point: { x: 1100, y: 600 },
    value:
      "i don't think they would do that when they've been hinting at her dying in the first half. Too predicatable IMO. I think lucas has to go tbh, he almost got an innocent man killed, and his acting has been bothering my ngl LOL",
    commentTimestamp: 1.55,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "mk.eth",
    likes: "-10",
    id: 9,
    point: { x: 526, y: 800 },
    value: "this past season was trash ngl",
    commentTimestamp: 1.49,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "matt",
    likes: "+93",
    id: 3,
    point: { x: 50, y: 600 },
    value:
      "aipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "br1an.eth",
    likes: "+6",
    id: 15,
    point: { x: 50, y: 500 },
    value:
      "sighh if only someone looked at me the way steve is looking at nancy right now",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "steveFan",
    likes: "-2",
    id: 16,
    point: { x: 900, y: 100 },
    value: "GIVE STEVE AND NANCY A HAPPY ENDING",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "steveFan",
    likes: "-2",
    id: 17,
    point: { x: 900, y: 150 },
    value: "lol remember when we all hated steve",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "steveFan",
    likes: "-2",
    id: 18,
    point: { x: 50, y: 150 },
    value: "STEVE >> WILL❤️❤️❤️",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "matt",
    likes: "+93",
    id: 19,
    point: { x: 450, y: 200 },
    value: "❤️❤️",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "matt",
    likes: "+93",
    id: 20,
    point: { x: 600, y: 175 },
    value: "❤️❤️",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "matt",
    likes: "+93",
    id: 5,
    point: { x: 1100, y: 320 },
    value:
      "d heard that the actors Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "matt",
    likes: "+93",
    id: 8,
    point: { x: 649, y: 723 },
    value: "lwills hair is way too long imo",
    commentTimestamp: 6,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
];

const fasterComments = [
  {
    username: "brian",
    likes: "+1",
    id: 11,
    point: { x: 600, y: 100 },
    value: "im so excited!!! lets gooooooo",
    commentTimestamp: 0.5,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "gwg.eth",
    likes: "+29",
    id: 12,
    point: { x: 620, y: 150 },
    value: "is this the last season?",
    commentTimestamp: 0.8,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "mk.eth",
    likes: "-10",
    id: 13,
    point: { x: 590, y: 200 },
    value: "it better not be bruh",
    commentTimestamp: 1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "matt",
    likes: "+93",
    id: 1,
    point: { x: 50, y: 50 },
    value: `I have a hypothesis on why sam is going to die. Vecna preys on people who are mentally weaker right, hence all the kids going to therapy at school and how they're suffering from all these symptons. its because vecna hijacks peoples brains like how El does.`,
    commentTimestamp: 1.1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "br1an.eth",
    likes: "+6",
    id: 2,
    point: { x: 50, y: 320 },
    value:
      "bipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    commentTimestamp: 1.1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "steveFan",
    likes: "-2",
    id: 4,
    point: { x: 1100, y: 50 },
    value:
      "c heard that the actors Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    commentTimestamp: 1.3,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "brian",
    likes: "+1",
    id: 6,
    point: { x: 1100, y: 520 },
    value: "do yall actually think they're killing Alex this season?",
    commentTimestamp: 1.5,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "gwg.eth",
    likes: "+29",
    id: 7,
    point: { x: 1100, y: 600 },
    value:
      "i don't think they would do that when they've been hinting at her dying in the first half. Too predicatable IMO. I think lucas has to go tbh, he almost got an innocent man killed, and his acting has been bothering my ngl LOL",
    commentTimestamp: 1.6,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "mk.eth",
    likes: "-10",
    id: 9,
    point: { x: 526, y: 800 },
    value: "this past season was trash ngl",
    commentTimestamp: 2.1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "matt",
    likes: "+93",
    id: 3,
    point: { x: 50, y: 600 },
    value:
      "aipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    commentTimestamp: 5.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "br1an.eth",
    likes: "+6",
    id: 15,
    point: { x: 50, y: 500 },
    value:
      "sighh if only someone looked at me the way steve is looking at nancy right now",
    commentTimestamp: 3.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "steveFan",
    likes: "-2",
    id: 16,
    point: { x: 900, y: 100 },
    value: "GIVE STEVE AND NANCY A HAPPY ENDING",
    commentTimestamp: 2.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "steveFan",
    likes: "-2",
    id: 17,
    point: { x: 900, y: 150 },
    value: "lol remember when we all hated steve",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "steveFan",
    likes: "-2",
    id: 18,
    point: { x: 50, y: 150 },
    value: "STEVE >> WILL❤️❤️❤️",
    commentTimestamp: 4.0,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "matt",
    likes: "+93",
    id: 19,
    point: { x: 450, y: 200 },
    value: "❤️❤️",
    commentTimestamp: 5.1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "matt",
    likes: "+93",
    id: 20,
    point: { x: 600, y: 175 },
    value: "❤️❤️",
    commentTimestamp: 7.3,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "matt",
    likes: "+93",
    id: 5,
    point: { x: 1100, y: 320 },
    value:
      "d heard that the actors Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    commentTimestamp: 6.53,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "matt",
    likes: "+93",
    id: 8,
    point: { x: 649, y: 723 },
    value: "lwills hair is way too long imo",
    commentTimestamp: 6,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
];

const demo1Comments = [
  {
    username: "livy",
    likes: "+1",
    id: 11,
    point: { x: 100, y: 100 },
    value: "Real life tinder? Is this my dream come true??",
    commentTimestamp: 0.2,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "Siddhartha Roy",
    likes: "+55",
    id: 12,
    point: { x: 75, y: 190 },
    value:
      "Lol no this is gonna be so awk for the guy to publicly swipe this would be my worst nightmare",
    commentTimestamp: 1.0,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "mrgn_ch",
    likes: "+1",
    id: 13,
    point: { x: 270, y: 300 },
    value: "absolutely horrifying omg",
    commentTimestamp: 3.4,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "br1an.eth",
    likes: "+93",
    id: 1,
    point: { x: 1300, y: 50 },
    value: `She was cute why did he swipe left!!`,
    commentTimestamp: 4.55,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "Mycah Ray",
    likes: "+270",
    id: 2,
    point: { x: 1300, y: 135 },
    value:
      "I don’t think he was swiping based on looks, majority of the women were pretty. I think he swiped based on reaction! Smiles or reception he liked, Irritated or non receptive he didnt",
    commentTimestamp: 5,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "Joan Muraguri",
    likes: "+108",
    id: 4,
    point: { x: 1300, y: 300 },
    value: "I’m positive he was swiping based on if they were smiling or not",
    commentTimestamp: 5.55,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "justkenzie",
    likes: "+680",
    id: 6,
    point: { x: 650, y: 80 },
    value:
      "imagine driving an hour drive to this shoot just to get swiped left on right at the beginning lol",
    commentTimestamp: 7.1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "leslie landberg",
    likes: "+1",
    id: 7,
    point: { x: 650, y: 800 },
    value: "Oh boy… this is the real moment of truth",
    commentTimestamp: 13,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "Virginia Serpas",
    likes: "+28",
    id: 9,
    point: { x: 50, y: 500 },
    value: "what a cutie, who would say no to anshul",
    commentTimestamp: 16.15,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "max_d",
    likes: "+11",
    id: 20,
    point: { x: 50, y: 100 },
    value: "i don’t have a good feeling about this",
    commentTimestamp: 17,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "zika",
    likes: "+65",
    id: 16,
    point: { x: 900, y: 100 },
    value: "ooohhhh nooooooo",
    commentTimestamp: 19.3,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "grace",
    likes: "+5",
    id: 17,
    point: { x: 600, y: 80 },
    value: "NOOOO WHY",
    commentTimestamp: 18.4,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "brian",
    likes: "+18",
    id: 8,
    point: { x: 649, y: 723 },
    value: "OMG EVERYONE IS LEAVING",
    commentTimestamp: 19.45,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "yoyo",
    likes: "+1",
    id: 19,
    point: { x: 60, y: 400 },
    value: "poor anshul🥺🥺🥺",
    commentTimestamp: 20,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "Lol Me",
    likes: "+1",
    id: 100,
    point: { x: 1280, y: 600 },
    value: "This is BRUTAL hahahhaha",
    commentTimestamp: 20.5,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "brooke",
    likes: "+2",
    id: 5,
    point: { x: 1300, y: 320 },
    value: "😭😭😭😭😭",
    commentTimestamp: 20.8,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "David Winner",
    likes: "+2",
    id: 101,
    point: { x: 1300, y: 400 },
    value: "💀RIP our boy anshul",
    commentTimestamp: 21,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "루태유",
    likes: "+91",
    id: 102,
    point: { x: 50, y: 723 },
    value:
      "i can’t believe everyone is leaving he’s so handsome and seems really sweet!! I would def give him a chance",
    commentTimestamp: 21.8,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "HitmanLowe3",
    likes: "+91",
    id: 103,
    point: { x: 50, y: 260 },
    value: "these girls are feeling the POWER lmao",
    commentTimestamp: 22.8,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "yeezy",
    likes: "+1007",
    id: 104,
    point: { x: 1250, y: 100 },
    value: "Lmao imagine if they all left and he just stood there",
    commentTimestamp: 24.5,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "rachel_g",
    likes: "+275",
    id: 105,
    point: { x: 1260, y: 180 },
    value: "I’m surprised so many left. He’s actually attractive",
    commentTimestamp: 24.7,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "sancho chingon",
    likes: "+275",
    id: 106,
    point: { x: 200, y: 100 },
    value: "I feel his pain lol",
    commentTimestamp: 24.7,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "Sai Kaushal",
    likes: "+80",
    id: 107,
    point: { x: 1265, y: 280 },
    value: "He's south asian tho. So yeah, society usually passes on them.",
    commentTimestamp: 25.1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "ava",
    likes: "-12",
    id: 108,
    point: { x: 1265, y: 380 },
    value:
      "yes people judge based on ethnicity. Like a lot of women don't want to date south Asian men cause of their negative stereotypes",
    commentTimestamp: 25.4,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "noor_clean",
    likes: "-5",
    id: 109,
    point: { x: 1240, y: 490 },
    value:
      "He has rich white people accent, i cant even see him as full indian 🤣🤣🤣i used to meet a lot of indian tho and they are not like this",
    commentTimestamp: 25.4,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "Tewodros Samson",
    likes: "+0",
    id: 110,
    point: { x: 1240, y: 570 },
    value: "maybe they just wanted to reject him because of fear of rejection",
    commentTimestamp: 25.7,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "gwg_ftw",
    likes: "+291",
    id: 111,
    point: { x: 50, y: 100 },
    value: "“ANSHUL-ada” i’m dead best intro ever",
    commentTimestamp: 33,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "Hazzahawk 371",
    likes: "+6",
    id: 112,
    point: { x: 50, y: 190 },
    value: "I’m so here for the puns",
    commentTimestamp: 34.1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },

  {
    username: "Radhika Arora",
    likes: "+18",
    id: 113,
    point: { x: 649, y: 723 },
    value: "who’s he gonna pick!!!",
    commentTimestamp: 34.1,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
  {
    username: "Niyaran Tuti",
    likes: "+101",
    id: 114,
    point: { x: 900, y: 100 },
    value: "ahhhhh shes literally the prettiest girl ive ever seen oml",
    commentTimestamp: 50,
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
  },
];

export { COLORS, topComments, fasterComments, demo1Comments };
