export const comments = [
  {
    id: 1,
    username: "br1an.eth",
    text: "i used to make pickled onions bc of kenji",
    isFCUser: false,
    color: "#FF6D6A",
    a: true,
    delay: "1s",
    // add 2 seconds to delay for each comment
  },
  {
    id: 2,
    username: "dwr.eth",
    text: "the chewing is so great",
    isFCUser: false,
    color: "#2616E2",
    a: false,
    delay: "2s",
  },
  {
    id: 3,
    username: null,
    text: "really increases the hunger",
    isFCUser: false,
    color: "#2616E2",
    a: false,
    delay: "3s",
  },
  {
    id: 4,
    username: "hiringdevs.eth",
    text: "rainbowspongedao wen",
    isFCUser: false,
    color: "#F2349A",
    a: false,
    delay: "6s",
  },
  {
    id: 5,
    username: "gracewhiteguan.eth",
    text: "minting rainbow sponge NFTs asap",
    isFCUser: false,
    color: "#10ABD2",
    a: false,
    delay: "8s",
  },
  {
    id: 6,
    username: "kochak.eth",
    text: "gtfo w that dab",
    isFCUser: true,
    color: "#3BAB83",
    a: false,
    delay: "10s",
  },
  {
    id: 7,
    username: "gregskril.eth",
    text: "when you realize brian dropped your own vid in the queue 🥵 ",
    isFCUser: true,
    color: "#517EF5",
    a: false,
    delay: "11s",
  },
  {
    id: 8,
    username: null,
    text: "Farcasters 🤝 Unlonely",
    isFCUser: true,
    color: "#517EF5",
    a: false,
    delay: "12s",
  },
  {
    id: 9,
    username: "kunalm.eth",
    text: "cooking hawk!",
    isFCUser: true,
    color: "#BB29BB",
    a: false,
    delay: "14s",
  },
  {
    id: 10,
    username: "popp.eth",
    text: "i love this idea - props to whoever picked this vid",
    isFCUser: true,
    color: "#006BCD",
    a: false,
    delay: "15s",
  },
  {
    id: 11,
    username: "chopan.eth",
    text: "✨🥳 fun vibe here",
    isFCUser: true,
    color: "#C653FC",
    a: false,
    delay: "17s",
  },
  {
    id: 12,
    username: "0x4...857",
    text: "damn imma hit the blunt in honor of this video",
    isFCUser: false,
    color: "#FF9900",
    a: false,
    delay: "19s",
  },
  {
    id: 13,
    username: null,
    text: "im bumping, need this to drop asap",
    isFCUser: false,
    color: "#FF9900",
    a: false,
    delay: "20s",
  },
  {
    id: 14,
    username: "0x6...BB9",
    text: "VOTE NATHAN GUYS",
    isFCUser: false,
    color: "#12A4AD",
    a: false,
    delay: "24s",
  },
  {
    id: 15,
    username: "lesgreys.eth",
    text: "gn all. love this!",
    isFCUser: true,
    color: "#4D14C5",
    a: false,
    delay: "26s",
  },
  {
    id: 16,
    username: "0x0...F8E",
    text: "@brian you’re mvp of the day. well done",
    isFCUser: false,
    color: "#49B747",
    a: false,
    delay: "28s",
  },
]